# study_content.py

study_content = {
    "Swing Points": {
        "Lesson 1.1: What Are Swing Points?": (
            "<p>Swing points are critical levels on a price chart where the direction of the price changes. "
            "They are categorized as:</p>"
            "<ul>"
            "<li><strong>Swing Highs</strong>: Peaks where the price hits a high before reversing downward. "
            "A swing high is identified when a candle's high exceeds the highs of the candles immediately before and after it.</li>"
            "<li><strong>Swing Lows</strong>: Troughs where the price hits a low before reversing upward. "
            "A swing low occurs when a candle's low is less than the lows of the two surrounding candles.</li>"
            "</ul>"
            "<p>These points are foundational for chart analysis and trend identification in your app's charting exams.</p>"
        ),
        "Lesson 1.2: Why Swing Points Matter": (
            "<p>Swing points are essential because:</p>"
            "<ul>"
            "<li><strong>They Define Trends</strong>: Higher swing highs and higher swing lows indicate an uptrend, "
            "while lower swing highs and lower swing lows signal a downtrend.</li>"
            "<li><strong>They Shape Market Structure</strong>: Swing points establish key support and resistance levels, "
            "often tested in your app's bias tests.</li>"
            "<li><strong>They Signal Reversals</strong>: A significant swing point can hint at a potential trend change "
            "when paired with other indicators.</li>"
            "</ul>"
            "<p>Mastering swing points will help you excel in trend-related questions in your app's quizzes.</p>"
        ),
        "Lesson 1.3: How to Identify Swing Points": (
            "<p>To spot swing points:</p>"
            "<ol>"
            "<li><strong>Find Turning Points</strong>: Look for candles where the price reverses direction.</li>"
            "<li><strong>Compare Neighboring Candles</strong>: For a swing high, confirm the candle's high is greater than "
            "the highs of the two adjacent candles. For a swing low, ensure the low is less than the lows of "
            "the two surrounding candles.</li>"
            "<li><strong>Filter Noise</strong>: Focus on prominent peaks and troughs, ignoring minor fluctuations that don't "
            "affect the broader trend.</li>"
            "</ol>"
            "<p>Practice this process to succeed in your app's charting exams.</p>"
        ),
        "Lesson 1.4: Real-World Example": (
            "<p>Consider Bitcoin on a daily chart:</p>"
            "<ul>"
            "<li><strong>Uptrend</strong>: Price drops to $40,000 (swing low), rises to $45,000 (swing high), falls to $42,000 "
            "(higher swing low), then climbs to $48,000 (higher swing high)—indicating an uptrend.</li>"
            "<li><strong>Downtrend</strong>: Price peaks at $50,000 (swing high), drops to $46,000 (swing low), rises to $48,000 "
            "(lower swing high), then falls to $43,000 (lower swing low)—signaling a downtrend.</li>"
            "</ul>"
            "<p>These patterns are similar to scenarios in your app's quizzes and bias tests.</p>"
        ),
        "Lesson 1.5: Applying Swing Points": (
            "<p>Use swing points practically by:</p>"
            "<ul>"
            "<li><strong>Drawing Trendlines</strong>: Connect swing lows in an uptrend or swing highs in a downtrend to visualize the trend.</li>"
            "<li><strong>Setting Stop-Losses</strong>: Place a stop-loss below a swing low when buying (or above a swing high when selling) to limit risk.</li>"
            "<li><strong>Finding Entry/Exit Points</strong>: Buy when the price bounces off a swing low in an uptrend, or sell near a swing high in a downtrend.</li>"
            "</ul>"
            "<p>These techniques align with tasks in your app's charting exams.</p>"
        ),
        "Quiz Preparation: Swing Points": (
            "<div class='quiz-prep'>"
            "<h4>Here's what you'll see in the quizzes, based on 'Swing Point Basics':</h4>"
            
            "<div class='question-preview'>"
            "<h5>Question 1: What does this chart indicate about Old High and Old Low levels?</h5>"
            "<ul class='options-list'>"
            "<li>They are simple support and resistance levels</li>"
            "<li>They represent trend reversal points</li>"
            "<li>They are liquidity pools for institutional orders</li>"
            "<li>They are just previous price levels</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> They are liquidity pools for institutional orders</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Old Highs and Old Lows represent significant liquidity pools where institutional orders gather, making them important targets for price movement. These levels often attract price action due to the concentration of stop losses or take profit orders from previous trades.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 2: What trading concept is illustrated in this range diagram?</h5>"
            "<ul class='options-list'>"
            "<li>Trend following</li>"
            "<li>Range boundaries</li>"
            "<li>Breakout patterns</li>"
            "<li>Support and resistance</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Range boundaries</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> The diagram shows how range boundaries are formed by swing highs and swing lows, creating tradeable areas in the market. Traders look for opportunities to buy near the lower boundary (support) and sell near the upper boundary (resistance), expecting the price to oscillate within this range.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 3: In this chart, what do the labeled \"Swing High\" and \"Swing Low\" points represent?</h5>"
            "<ul class='options-list'>"
            "<li>Points where price action reversed</li>"
            "<li>Points where volume was highest</li>"
            "<li>Points where liquidity was removed</li>"
            "<li>Points where market orders were executed</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Points where price action reversed</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Swing Highs and Swing Lows in this chart are points where the price action reversed, indicating potential areas for future support or resistance. These points are crucial for identifying trend changes or continuation patterns in technical analysis.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 4: Why is understanding the concept of swing points important for traders?</h5>"
            "<ul class='options-list'>"
            "<li>To predict market sentiment</li>"
            "<li>To identify entry and exit points</li>"
            "<li>To gauge market volatility</li>"
            "<li>To track institutional trading</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> To identify entry and exit points</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Swing points are critical for traders to identify optimal entry and exit points in the market. They help in setting stop losses, take profit levels, and in recognizing potential trend reversals or continuations based on past price action.</p>"
            "</div>"
            "</div>"
            
            "<div class='tips-section'>"
            "<h5>Tips for Success:</h5>"
            "<ul class='tips-list'>"
            "<li><strong>Context is Key</strong>: Questions might focus on liquidity (e.g., Old Highs/Lows) or price action (e.g., reversals). Read carefully.</li>"
            "<li><strong>Definitions Matter</strong>: Swing points are defined by neighboring candles—don't confuse them with random highs/lows.</li>"
            "<li><strong>Practical Focus</strong>: Think about how swing points are used (entries, exits, ranges) when picking answers.</li>"
            "</ul>"
            "</div>"
            "</div>"
        )
    },
    "Market Structure": {
        "Lesson 2.1: What Is Market Structure?": (
            "<p>Market structure refers to the overall framework of price behavior, including trends, ranges, and key levels like support and resistance. "
            "It helps traders understand the current state of the market and make informed decisions.</p>"
        ),
        "Lesson 2.2: Why Market Structure Matters": (
            "<p>Understanding market structure is crucial because:</p>"
            "<ul>"
            "<li><strong>It Shapes Strategies</strong>: Different structures (trending, ranging) require different trading approaches.</li>"
            "<li><strong>It Identifies Key Levels</strong>: Support and resistance levels guide entry and exit points.</li>"
            "<li><strong>It Aligns Trades with the Market</strong>: Trading with the structure reduces the risk of fighting against the prevailing trend.</li>"
            "</ul>"
        ),
        "Lesson 2.3: How to Identify Market Structure": (
            "<p>To identify market structure:</p>"
            "<ol>"
            "<li><strong>Map Swing Points</strong>: Higher highs and higher lows indicate an uptrend; lower highs and lower lows indicate a downtrend.</li>"
            "<li><strong>Spot Ranges</strong>: Horizontal support and resistance zones suggest a ranging market.</li>"
            "<li><strong>Detect Breakouts</strong>: A breakout with volume can shift the market from a range to a trend.</li>"
            "</ol>"
        ),
        "Lesson 2.4: Real-World Example": (
            "<p>For example, if Bitcoin is making higher highs and higher lows, it's in an uptrend. If it's oscillating between two price levels, it's in a range.</p>"
        ),
        "Lesson 2.5: Applying Market Structure": (
            "<p>Apply market structure by:</p>"
            "<ul>"
            "<li><strong>Trading Trends</strong>: Buy pullbacks in uptrends or sell rallies in downtrends.</li>"
            "<li><strong>Trading Ranges</strong>: Buy at support and sell at resistance.</li>"
            "<li><strong>Trading Breakouts</strong>: Enter on confirmed breakouts with volume.</li>"
            "</ul>"
        ),
        "Quiz Preparation: Market Structure": (
            "<div class='quiz-prep'>"
            "<h4>Here's what to expect in the quizzes:</h4>"
            
            "<div class='question-preview'>"
            "<h5>Question 1: What do equal lows indicate in this chart pattern?</h5>"
            "<ul class='options-list'>"
            "<li>Trend reversal</li>"
            "<li>Continuation pattern</li>"
            "<li>Liquidity pool</li>"
            "<li>Random price action</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Liquidity pool</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Equal lows indicate a liquidity pool where stop orders accumulate, making it a target for larger players. These levels are significant because they often lead to price movements when the stop orders are triggered, providing liquidity to the market.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 2: How are swing points validated in this chart example?</h5>"
            "<ul class='options-list'>"
            "<li>By time duration</li>"
            "<li>By price level only</li>"
            "<li>By surrounding price action</li>"
            "<li>By volume</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> By surrounding price action</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Swing points are validated by the surrounding price action creating higher highs/lows or lower highs/lows. This validation confirms the strength or weakness of these points as potential support or resistance levels, influencing trading decisions.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 3: What role do swing highs and lows play in defining market structure?</h5>"
            "<ul class='options-list'>"
            "<li>They define trend lines</li>"
            "<li>They outline support and resistance levels</li>"
            "<li>They indicate market phases</li>"
            "<li>They predict future price movements</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> They outline support and resistance levels</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Swing highs and lows play a crucial role in defining market structure by outlining key support and resistance levels. These levels help traders understand the current market structure, whether it's trending, ranging, or showing signs of reversal.</p>"
            "</div>"
            "</div>"
            
            "<div class='tips-section'>"
            "<h5>Tips for Success:</h5>"
            "<ul class='tips-list'>"
            "<li><strong>Swing Points Rule</strong>: They're the backbone of market structure—know how they set up trends and ranges.</li>"
            "<li><strong>Liquidity Link</strong>: Equal highs/lows often tie to liquidity pools, so watch for that angle.</li>"
            "<li><strong>Price Action Focus</strong>: Validation comes from surrounding candles, not just volume or time.</li>"
            "</ul>"
            "</div>"
            "</div>"
        )
    },
    "Liquidity Concepts": {
        "Lesson 3.1: What Is Liquidity in Trading?": (
            "<p>Liquidity refers to the availability of buy and sell orders in the market. High liquidity areas are where large orders cluster, often around key levels like swing highs and lows.</p>"
        ),
        "Lesson 3.2: Why Liquidity Matters": (
            "<p>Liquidity is important because:</p>"
            "<ul>"
            "<li><strong>It Affects Order Execution</strong>: High liquidity reduces slippage.</li>"
            "<li><strong>It Attracts Price</strong>: Price often moves toward liquidity pools to fill orders.</li>"
            "<li><strong>It Signals Institutional Activity</strong>: Large players target liquidity for better execution.</li>"
            "</ul>"
        ),
        "Lesson 3.3: How to Identify Liquidity Pools": (
            "<p>Identify liquidity pools by:</p>"
            "<ol>"
            "<li><strong>Looking at Swing Highs and Lows</strong>: These often have stop orders clustered above or below.</li>"
            "<li><strong>Observing Equal Highs or Lows</strong>: These can indicate stop-loss clusters.</li>"
            "<li><strong>Analyzing Volume</strong>: High volume areas often coincide with liquidity.</li>"
            "</ol>"
        ),
        "Lesson 3.4: Real-World Example": (
            "<p>For instance, if Bitcoin repeatedly tests a swing low without breaking it, there may be a liquidity pool of buy orders there.</p>"
        ),
        "Lesson 3.5: Applying Liquidity Concepts": (
            "<p>Use liquidity concepts by:</p>"
            "<ul>"
            "<li><strong>Targeting Liquidity for Entries</strong>: Enter trades near liquidity pools where price might reverse.</li>"
            "<li><strong>Setting Stops Beyond Liquidity</strong>: Place stop-losses outside of liquidity zones to avoid being swept.</li>"
            "<li><strong>Watching for Liquidity Grabs</strong>: Be cautious of price moves that trigger stop orders before reversing.</li>"
            "</ul>"
        ),
        "Quiz Preparation: Liquidity Concepts": (
            "<div class='quiz-prep'>"
            "<h4>Quiz questions you'll face:</h4>"
            
            "<div class='question-preview'>"
            "<h5>Question 1: What type of orders create sellside liquidity as shown?</h5>"
            "<ul class='options-list'>"
            "<li>Stop losses from long trades</li>"
            "<li>Take profit from shorts</li>"
            "<li>Market buy orders</li>"
            "<li>Limit sell orders</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Stop losses from long trades</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Sellside liquidity is created primarily by stop losses from long trades being clustered at certain levels, leading to sell orders when those levels are hit. This phenomenon can cause price to move significantly as these orders are executed.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 2: In the buyside liquidity diagram, what does the green box represent?</h5>"
            "<ul class='options-list'>"
            "<li>Take profit area</li>"
            "<li>Entry zone</li>"
            "<li>Stop loss cluster</li>"
            "<li>Accumulation area</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Accumulation area</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> The green box represents an accumulation area where buyside liquidity pools form from clustered buy orders, indicating a zone where traders are looking to enter long positions. This area often acts as a support level where buying pressure can increase.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 3: Why is understanding liquidity important for trading strategies?</h5>"
            "<ul class='options-list'>"
            "<li>To find the best times to trade</li>"
            "<li>To manage trade sizes effectively</li>"
            "<li>To predict market movements</li>"
            "<li>To reduce slippage in order execution</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> To reduce slippage in order execution</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Understanding liquidity is crucial for trading strategies because it helps in reducing slippage during order execution. High liquidity areas ensure that large orders can be filled at desired prices with minimal price impact, which is vital for both entry and exit strategies.</p>"
            "</div>"
            "</div>"
            
            "<div class='tips-section'>"
            "<h5>Tips for Success:</h5>"
            "<ul class='tips-list'>"
            "<li><strong>Buy vs. Sell</strong>: Buyside liquidity = buy orders (e.g., short stop losses); sellside = sell orders (e.g., long stop losses).</li>"
            "<li><strong>Practical Impact</strong>: Focus on how liquidity affects execution—slippage is a big deal.</li>"
            "<li><strong>Spot the Pools</strong>: Look for clusters at swing points or equal levels.</li>"
            "</ul>"
            "</div>"
            "</div>"
        )
    },
    "Risk Management": {
        "Lesson 4.1: What Is Risk Management in Trading?": (
            "<p>Risk management involves strategies to minimize losses and protect capital. It's essential for long-term trading success.</p>"
        ),
        "Lesson 4.2: Why Risk Management Matters": (
            "<p>Effective risk management:</p>"
            "<ul>"
            "<li><strong>Preserves Capital</strong>: Limits losses on individual trades.</li>"
            "<li><strong>Enhances Consistency</strong>: Helps maintain a steady equity curve.</li>"
            "<li><strong>Reduces Emotional Stress</strong>: Provides a clear plan for handling losses.</li>"
            "</ul>"
        ),
        "Lesson 4.3: Key Risk Management Techniques": (
            "<p>Key techniques include:</p>"
            "<ol>"
            "<li><strong>Position Sizing</strong>: Determine how much to risk per trade (e.g., 1-2% of capital).</li>"
            "<li><strong>Stop-Loss Orders</strong>: Set predefined exit points to limit losses.</li>"
            "<li><strong>Risk-Reward Ratios</strong>: Aim for trades where potential reward outweighs risk (e.g., 1:3 ratio).</li>"
            "</ol>"
        ),
        "Lesson 4.4: Real-World Example": (
            "<p>For example, if your account size is $10,000 and you risk 1% per trade, your maximum loss per trade is $100. If your stop-loss is $10 away from entry, you can trade 10 shares.</p>"
        ),
        "Lesson 4.5: Applying Risk Management": (
            "<p>Apply risk management by:</p>"
            "<ul>"
            "<li><strong>Calculating Position Size</strong>: Use a formula like (Account Size * Risk %) / Stop-Loss Distance.</li>"
            "<li><strong>Setting Stop-Losses</strong>: Place them at logical levels, such as below support or above resistance.</li>"
            "<li><strong>Evaluating Risk-Reward</strong>: Only take trades where the potential reward justifies the risk.</li>"
            "</ul>"
        ),
        "Quiz Preparation: Risk Management": (
            "<div class='quiz-prep'>"
            "<h4>Get ready for these quiz questions:</h4>"
            
            "<div class='question-preview'>"
            "<h5>Question 1: What is the optimal risk:reward ratio shown for premium zone trades?</h5>"
            "<ul class='options-list'>"
            "<li>1:1</li>"
            "<li>1:2</li>"
            "<li>1:3</li>"
            "<li>2:1</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> 1:3</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> The diagram shows a 1:3 risk:reward ratio as optimal for trades into premium zones. Trading in premium zones often involves higher risk, so a favorable reward ratio like 1:3 helps to justify the risk taken.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 2: When looking to take long trades, which zone provides better risk:reward?</h5>"
            "<ul class='options-list'>"
            "<li>Premium zone</li>"
            "<li>Discount zone</li>"
            "<li>Both zones equally</li>"
            "<li>Neither zone</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Discount zone</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> The discount zone provides a better risk:reward ratio for long trades as shown by the reward/risk boxes. Entering a trade in a discount zone means buying at a lower price with the expectation of selling at a higher price, enhancing potential returns relative to the risk.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 3: What strategic advantage does trading in discount zones offer?</h5>"
            "<ul class='options-list'>"
            "<li>Lower entry costs</li>"
            "<li>Higher probability of profit</li>"
            "<li>Reduced risk of slippage</li>"
            "<li>All of the above</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> All of the above</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Trading in discount zones offers several strategic advantages: lower entry costs since you're buying at a lower price, a potentially higher probability of profit due to the favorable risk:reward ratio, and reduced risk of slippage because of the higher liquidity often found at these levels.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 4: Why might traders prefer premium zones for short trades?</h5>"
            "<ul class='options-list'>"
            "<li>To capitalize on overbought conditions</li>"
            "<li>For lower risk entry</li>"
            "<li>To benefit from high liquidity</li>"
            "<li>For immediate profit taking</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> To capitalize on overbought conditions</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Traders might prefer premium zones for short trades to capitalize on overbought conditions. When prices are in premium zones, they are considered relatively high, offering a potential for price correction or reversal, which is ideal for shorting with a good risk:reward setup.</p>"
            "</div>"
            "</div>"
            
            "<div class='tips-section'>"
            "<h5>Tips for Success:</h5>"
            "<ul class='tips-list'>"
            "<li><strong>Zones Explained</strong>: Premium = expensive (good for shorts); discount = cheap (good for longs).</li>"
            "<li><strong>Risk-Reward</strong>: Always tie answers back to how it affects profitability.</li>"
            "<li><strong>Multi-Benefit</strong>: 'All of the above' can be a trap—check if every option really fits.</li>"
            "</ul>"
            "</div>"
            "</div>"
        )
    },
    "Fibonacci Retracement": {
        "Lesson 5.1: What Is Fibonacci Retracement?": (
            "<p>Fibonacci retracement is a tool that uses ratios (23.6%, 38.2%, 50%, 61.8%, 78.6%) to identify potential support or resistance levels after a price move.</p>"
        ),
        "Lesson 5.2: Why Fibonacci Retracement Matters": (
            "<p>Fibonacci retracement is valuable because:</p>"
            "<ul>"
            "<li><strong>It Predicts Pullbacks</strong>: It identifies where price might pause or reverse during a correction.</li>"
            "<li><strong>It Improves Timing</strong>: Traders use these levels to optimize entries and exits.</li>"
            "<li><strong>It Works with Other Tools</strong>: It often aligns with swing points or order blocks.</li>"
            "</ul>"
        ),
        "Lesson 5.3: How to Identify Fibonacci Levels": (
            "<p>To use Fibonacci retracement:</p>"
            "<ol>"
            "<li><strong>Select Swing Points</strong>: Choose a swing low and high (uptrend) or high and low (downtrend).</li>"
            "<li><strong>Draw the Tool</strong>: From low to high (uptrend) or high to low (downtrend).</li>"
            "<li><strong>Focus on Key Levels</strong>: 38.2%, 50%, 61.8% are most respected.</li>"
            "</ol>"
        ),
        "Lesson 5.4: Real-World Example": (
            "<p>If Bitcoin rises from $30,000 to $40,000, the 50% level at $35,000 may act as support during a pullback.</p>"
        ),
        "Lesson 5.5: Applying Fibonacci Retracement": (
            "<p>Apply it by:</p>"
            "<ul>"
            "<li><strong>Entering Trades</strong>: Buy at key levels during pullbacks.</li>"
            "<li><strong>Setting Stop-Losses</strong>: Place stops just beyond Fibonacci levels.</li>"
            "<li><strong>Taking Profits</strong>: Target the next Fibonacci level or extension.</li>"
            "</ul>"
        ),
        "Quiz Preparation: Fibonacci Retracement": (
            "<div class='quiz-prep'>"
            "<h4>Quiz questions from 'Optimal Trade Entry (Fibonacci Levels)':</h4>"
            
            "<div class='question-preview'>"
            "<h5>Question 1: What does the OTE (Optimal Trade Entry) range represent in the context of a long trade?</h5>"
            "<ul class='options-list'>"
            "<li>The range where stop losses should be placed</li>"
            "<li>The most favorable entry points for a long trade</li>"
            "<li>The area where the price is expected to reverse</li>"
            "<li>The zone where liquidity is highest</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> The most favorable entry points for a long trade</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> The OTE range from 0.62 to 0.79 represents the most favorable entry points for a long trade. This range is derived from Fibonacci retracement levels, where traders often find value in entering trades due to the potential for price to continue its upward trend after retracing to these levels.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 2: What is the midpoint of the OTE range for both long and short trades?</h5>"
            "<ul class='options-list'>"
            "<li>0.5</li>"
            "<li>0.62</li>"
            "<li>0.705</li>"
            "<li>0.79</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> 0.705</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> The midpoint of the OTE range, as shown in the image, is 0.705. This midpoint is significant as it is often considered a key level within the Fibonacci retracement where price might find support or resistance, making it a focal point for entry decisions.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 3: In the context of a short trade, where should the OTE be located relative to the price movement?</h5>"
            "<ul class='options-list'>"
            "<li>Between 0 and 0.5</li>"
            "<li>Between 0.5 and 0.62</li>"
            "<li>Between 0.62 and 0.79</li>"
            "<li>Above 0.79</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Between 0.62 and 0.79</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> For a short trade, the OTE should be located between 0.62 and 0.79 of the price movement, as shown in the image. This range is ideal for entering a short position because it captures the retracement levels where price might struggle to continue upward, providing a good risk/reward setup for shorts.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 4: Why is the OTE range significant in trading strategies?</h5>"
            "<ul class='options-list'>"
            "<li>It indicates where the market will definitely reverse</li>"
            "<li>It helps identify areas with the least volatility</li>"
            "<li>It provides a statistical edge in entry points</li>"
            "<li>It shows where institutional traders place their orders</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> It provides a statistical edge in entry points</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> The OTE range is significant because it provides traders with a statistical edge in choosing entry points. Based on Fibonacci levels, this range has historically proven to be areas where price reactions are common, offering traders a higher probability setup for both long and short trades.</p>"
            "</div>"
            "</div>"
            
            "<div class='tips-section'>"
            "<h5>Tips for Success:</h5>"
            "<ul class='tips-list'>"
            "<li><strong>OTE Range</strong>: Lock in 0.62–0.79 and its midpoint (0.705)—these are quiz favorites.</li>"
            "<li><strong>Long vs. Short</strong>: Same range applies, but context (uptrend vs. downtrend) changes the trade type.</li>"
            "<li><strong>Stats, Not Certainties</strong>: OTE is about probability, not guarantees—watch for trick options.</li>"
            "</ul>"
            "</div>"
            "</div>"
        )
    },
    "Fair Value Gaps": {
        "Lesson 6.1: What Are Fair Value Gaps?": (
            "<p>Fair Value Gaps (FVGs) are price ranges where rapid movement leaves a gap between candles with minimal trading activity. "
            "These gaps often attract price back to 'fill' them later.</p>"
        ),
        "Lesson 6.2: Why FVGs Matter": (
            "<p>FVGs are significant because:</p>"
            "<ul>"
            "<li><strong>They Draw Price Back</strong>: Markets tend to revisit FVGs, making them support or resistance zones.</li>"
            "<li><strong>They Create Opportunities</strong>: Traders use FVGs for entries and exits.</li>"
            "<li><strong>They Show Imbalances</strong>: FVGs reflect rapid sentiment shifts.</li>"
            "</ul>"
        ),
        "Lesson 6.3: How to Identify FVGs": (
            "<p>To identify FVGs:</p>"
            "<ol>"
            "<li><strong>Spot Gaps</strong>: Look for areas where consecutive candles don't overlap.</li>"
            "<li><strong>Determine Type</strong>: Bullish FVGs are below price after an upward move; bearish FVGs are above after a downward move.</li>"
            "<li><strong>Use Lower Timeframes</strong>: FVGs are clearer on 15-minute or 1-hour charts.</li>"
            "</ol>"
        ),
        "Lesson 6.4: Real-World Example": (
            "<p>For instance, if Bitcoin jumps from $50,000 to $51,000 with no trades in between, that's a bullish FVG.</p>"
        ),
        "Lesson 6.5: Applying FVGs": (
            "<p>Trade FVGs by:</p>"
            "<ul>"
            "<li><strong>Using as Levels</strong>: Buy at bullish FVGs or sell at bearish ones.</li>"
            "<li><strong>Setting Targets</strong>: Take profits when price fills the FVG.</li>"
            "<li><strong>Combining Signals</strong>: Pair FVGs with other patterns for stronger setups.</li>"
            "</ul>"
        ),
        "Quiz Preparation: Fair Value Gaps": (
            "<div class='quiz-prep'>"
            "<h4>From 'Fair Value Gaps'—here's what's coming:</h4>"
            
            "<div class='question-preview'>"
            "<h5>Question 1: What does the term \"Bullish FVG\" (BISI) stand for?</h5>"
            "<ul class='options-list'>"
            "<li>Buyside Imbalance/Sellside Inefficiency</li>"
            "<li>Sellside Imbalance/Buyside Inefficiency</li>"
            "<li>Buyside Inefficiency/Sellside Imbalance</li>"
            "<li>Sellside Efficiency/Buyside Imbalance</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Buyside Imbalance/Sellside Inefficiency</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Bullish FVG stands for Buyside Imbalance/Sellside Inefficiency. This occurs when there is a gap between the price action of the first and third candles, indicating a bullish sentiment due to more buying pressure than selling.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 2: What condition must be met for a Bearish FVG (SIBI) to form?</h5>"
            "<ul class='options-list'>"
            "<li>The first candle's high overlaps with the third candle's low</li>"
            "<li>The first candle's low does not overlap with the third candle's high</li>"
            "<li>The second candle's high overlaps with the first candle's low</li>"
            "<li>The third candle's low overlaps with the first candle's high</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> The first candle's low does not overlap with the third candle's high</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> For a Bearish FVG to form, the first candle's low must not overlap with the third candle's high, creating a gap that signifies a sellside imbalance and buyside inefficiency, indicating bearish sentiment.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 3: What is a key characteristic of a Fair Value Gap as described?</h5>"
            "<ul class='options-list'>"
            "<li>It is a single candle pattern</li>"
            "<li>It involves four candles with overlapping shadows</li>"
            "<li>It hides a gap between the shadows of the first and third candle in a three-candle pattern</li>"
            "<li>It shows a continuous upward or downward trend without gaps</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> It hides a gap between the shadows of the first and third candle in a three-candle pattern</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> A Fair Value Gap is characterized by a three-candle pattern where there is a hidden gap between the first and third candle's shadows. This gap is significant because it can indicate areas where price might return to fill the gap.</p>"
            "</div>"
            "</div>"
            
            "<div class='tips-section'>"
            "<h5>Tips for Success:</h5>"
            "<ul class='tips-list'>"
            "<li><strong>BISI vs. SIBI</strong>: Bullish = buying pressure (BISI); Bearish = selling pressure (SIBI).</li>"
            "<li><strong>Three Candles</strong>: FVGs are always a three-candle deal—watch for that gap between 1 and 3.</li>"
            "<li><strong>Imbalance Focus</strong>: It's about supply/demand mismatches, not just random gaps.</li>"
            "</ul>"
            "</div>"
            "</div>"
        )
    },
    "Order Blocks": {
        "Lesson 7.1: What Are Order Blocks?": (
            "<p>Order blocks are price zones where large institutional orders triggered significant moves. They're identified as the last candle before a sharp rally (bullish) or drop (bearish) and act as future support or resistance.</p>"
        ),
        "Lesson 7.2: Why Order Blocks Matter": (
            "<p>Order blocks are key because:</p>"
            "<ul>"
            "<li><strong>They Offer Strong Zones</strong>: These areas often hold due to institutional activity.</li>"
            "<li><strong>They Show Intent</strong>: They reveal where big players acted.</li>"
            "<li><strong>They Guide Entries</strong>: Order blocks help time trades precisely.</li>"
            "</ul>"
        ),
        "Lesson 7.3: How to Identify Order Blocks": (
            "<p>To locate order blocks:</p>"
            "<ol>"
            "<li><strong>Find a Big Move</strong>: Identify a sharp rally or drop.</li>"
            "<li><strong>Spot the Trigger</strong>: For a bullish order block, it's the last bearish candle before the rally; for bearish, the last bullish candle before the drop.</li>"
            "<li><strong>Mark the Range</strong>: Highlight the candle's high-to-low zone.</li>"
            "</ol>"
        ),
        "Lesson 7.4: Real-World Example": (
            "<p>If Bitcoin rallies from $40,000 to $45,000, the last bearish candle at $40,000 is a bullish order block.</p>"
        ),
        "Lesson 7.5: Applying Order Blocks": (
            "<p>Use order blocks by:</p>"
            "<ul>"
            "<li><strong>Entering Trades</strong>: Buy at bullish order blocks with confirmation.</li>"
            "<li><strong>Setting Stop-Losses</strong>: Place stops outside the block's range.</li>"
            "<li><strong>Confirming Signals</strong>: Look for reversal patterns at the block.</li>"
            "</ul>"
        ),
        "Quiz Preparation: Order Blocks": (
            "<div class='quiz-prep'>"
            "<h4>From 'Order_Block_Analysis'—quiz prep:</h4>"
            
            "<div class='question-preview'>"
            "<h5>Question 1: What defines this bullish order block formation and its significance?</h5>"
            "<ul class='options-list'>"
            "<li>Random bearish candles with no structure</li>"
            "<li>Bearish candles sweeping SSL before breaking structure up</li>"
            "<li>Only the color sequence of the candles</li>"
            "<li>The length of consolidation beforehand</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Bearish candles sweeping SSL before breaking structure up</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> A valid bullish order block shows bearish candles sweeping sellside liquidity (SSL) before breaking structure upwards, indicating institutional positioning before a move up.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 2: Analyzing this order block formation, what sequence validates its effectiveness?</h5>"
            "<ul class='options-list'>"
            "<li>Just the size of the candles</li>"
            "<li>The sweep of liquidity followed by BOS</li>"
            "<li>The number of candles involved</li>"
            "<li>Only the final breakout candle</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> The sweep of liquidity followed by BOS</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Effectiveness is validated by the clear sequence: liquidity sweep (taking out stops) followed by a break of structure (BOS), showing deliberate institutional manipulation.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 3: How does this order block's location affect its probability?</h5>"
            "<ul class='options-list'>"
            "<li>Lower probability due to multiple rejections</li>"
            "<li>Higher probability from clean liquidity sweep and BOS</li>"
            "<li>Probability only depends on candle size</li>"
            "<li>Location has no impact on probability</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Higher probability from clean liquidity sweep and BOS</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> The order block shows high probability characteristics through its clean sweep of liquidity and decisive break of structure, positioned at a key market structure level.</p>"
            "</div>"
            "</div>"
            
            "<div class='tips-section'>"
            "<h5>Tips for Success:</h5>"
            "<ul class='tips-list'>"
            "<li><strong>Sequence is Everything</strong>: Look for sweep → BOS—it's the institutional fingerprint.</li>"
            "<li><strong>Probability Clues</strong>: Clean setups with big moves = high probability.</li>"
            "<li><strong>Not Random</strong>: Order blocks are specific candles before big shifts—don't guess.</li>"
            "</ul>"
            "</div>"
            "</div>"
        )
    },
    "Volume Imbalance": {
        "Lesson 8.1: What Is Volume Imbalance?": (
            "<p>Volume imbalance is a significant disparity between buying and selling activity, often causing rapid price shifts. "
            "It's visible through volume spikes on a chart.</p>"
        ),
        "Lesson 8.2: Why Volume Imbalance Matters": (
            "<p>It's critical because:</p>"
            "<ul>"
            "<li><strong>It Confirms Moves</strong>: High volume validates price trends, a quiz focus.</li>"
            "<li><strong>It Signals Reversals</strong>: Low volume during a move suggests weakness.</li>"
            "<li><strong>It Supports Breakouts</strong>: High volume breakouts are more sustainable, key in charting exams.</li>"
            "</ul>"
        ),
        "Lesson 8.3: How to Identify Volume Imbalance": (
            "<p>To detect it:</p>"
            "<ol>"
            "<li><strong>Analyze Volume Bars</strong>: Look for spikes well above average volume.</li>"
            "<li><strong>Pair with Price</strong>: High volume with a large candle confirms strong pressure.</li>"
            "<li><strong>Check Divergence</strong>: Rising price with falling volume may indicate a weakening trend.</li>"
            "</ol>"
            "<p>For example, Bitcoin breaking $50,000 with a volume spike shows a bullish imbalance.</p>"
        ),
        "Lesson 8.4: Real-World Example": (
            "<p>Examples include:</p>"
            "<ul>"
            "<li><strong>Bullish Move</strong>: Bitcoin jumps from $45,000 to $47,000 with high volume, confirming strength.</li>"
            "<li><strong>Weak Move</strong>: Price rises from $48,000 to $49,000 with low volume, hinting at unsustainability.</li>"
            "</ul>"
            "<p>These match volume questions in your quizzes.</p>"
        ),
        "Lesson 8.5: Applying Volume Imbalance": (
            "<p>Use it by:</p>"
            "<ul>"
            "<li><strong>Confirming Entries</strong>: Trade when volume aligns with price direction.</li>"
            "<li><strong>Avoiding Traps</strong>: Skip moves with low volume that may reverse.</li>"
            "<li><strong>Spotting Reversals</strong>: Exit if volume diverges from price (e.g., price up, volume down).</li>"
            "</ul>"
            "<p>This will enhance your bias tests and charting exams.</p>"
        ),
        "Quiz Preparation: Volume Imbalance": (
            "<div class='quiz-prep'>"
            "<h4>Key Volume Imbalance Quiz Concepts:</h4>"
            
            "<div class='question-preview'>"
            "<h5>Question 1: What does high volume during a price breakout indicate?</h5>"
            "<ul class='options-list'>"
            "<li>The breakout is likely to fail</li>"
            "<li>The breakout has strong conviction and is more likely to be sustainable</li>"
            "<li>Market manipulation is occurring</li>"
            "<li>Institutional traders are exiting their positions</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> The breakout has strong conviction and is more likely to be sustainable</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> High volume during a price breakout indicates strong market conviction and participation, making the breakout more likely to be sustained. This shows genuine buying or selling pressure rather than a false move.</p>"
            "</div>"
            "</div>"
            
            "<div class='question-preview'>"
            "<h5>Question 2: What type of volume pattern would suggest a potential reversal?</h5>"
            "<ul class='options-list'>"
            "<li>Consistently high volume in the direction of the trend</li>"
            "<li>No noticeable change in volume</li>"
            "<li>Declining volume as price continues in the same direction</li>"
            "<li>Volume spikes on small price movements</li>"
            "</ul>"
            "<p><strong>Correct Answer:</strong> Declining volume as price continues in the same direction</p>"
            "<div class='explanation'>"
            "<p><strong>Explanation:</strong> Declining volume as price continues in the same direction suggests weakening momentum and conviction in the current trend, potentially signaling an upcoming reversal. This volume divergence is a key warning sign for traders.</p>"
            "</div>"
            "</div>"
            
            "<div class='tips-section'>"
            "<h5>Tips for Success:</h5>"
            "<ul class='tips-list'>"
            "<li><strong>Volume Confirms Price</strong>: Strong moves should be accompanied by increased volume.</li>"
            "<li><strong>Look for Divergences</strong>: When price and volume move in opposite directions, be cautious.</li>"
            "<li><strong>Context Matters</strong>: Volume at support/resistance levels is more significant than at random areas.</li>"
            "</ul>"
            "</div>"
            "</div>"
        )
    }
}